export const Data = [
    {
      id: 1,
      title: "OnePlus Nord",
      description: "black in color",
      category: "Mobile",
      price:2500,
      img: "https://m.media-amazon.com/images/I/71PQwaroG3S._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "Redmi 9",
      description: "black in color",
      category: "Mobile",
      price: 3500,
      img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "Iphone 12",
      description: "Best mobile ever",
      category: "Mobile",
      price: 90500,
      img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
      quantity: 1,
    },
    {
        id: 4,
        title: "OnePlus Nord CE 5G ",
        category: "Mobile",
        description: "(Blue Void, 8GB RAM, 128GB Storage)",
        price: 24999,
        img: "https://m.media-amazon.com/images/I/61iy2Ru9KdS._SL1500_.jpg",
        quantity: 1,
      },
      {
        id: 5,
        title: "Allen Solly Men's Sweatshirt",
        description: "Care Instructions: Machine Wash",
        category: "Men",
        price:769.00,
        img: "https://m.media-amazon.com/images/I/51vb7LJ3oQL._UL1500_.jpg",
        quantity: 1,
      },
      {
        id: 6,
        title: "Allen Solly Men's Jacket",
        description: "Care Instructions: Machine Wash",
        category: "Men",
        price: 1129.00,
        img: "https://m.media-amazon.com/images/I/61mGSAIep+L._UL1500_.jpg",
        quantity: 1,
      },
      {
        id: 7,
        title: "Bomber Jacket",
        description: "Ben Martin Men's Quilted ",
        category: "Men",
        price: 999,
        img: "https://m.media-amazon.com/images/I/61H5pIwnCdL._UL1500_.jpg",
        quantity: 1,
      },
      {
          id: 8,
          title: "Red Tape Men's Sweatshirt",
          description: "(Blue Void, 8GB RAM, 128GB Storage)",
          category: "Men",
          price: 830,
          img: "https://m.media-amazon.com/images/I/71fO57EBeaL._UL1500_.jpg",
          quantity: 1,
        },
   
  ];